import os
import re
import logging
from typing import List, Dict, Any
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image, PageBreak, KeepTogether
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.pdfgen import canvas

logger = logging.getLogger(__name__)

class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas to calculate total page count and draw running headers/footers.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_elements(num_pages)
            super().showPage()
        super().save()

    def draw_page_elements(self, page_count):
        # Do not draw headers/footers on page 1 (Title Page)
        if self._pageNumber == 1:
            return
            
        self.saveState()
        
        # Colors
        text_color = colors.HexColor("#4B5563") # Slate Gray
        border_color = colors.HexColor("#E5E7EB") # Light Gray
        
        # Header
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#1E3A8A")) # Dark Blue
        self.drawString(54, 750, "AUTONOMOUS RESEARCH REPORT")
        
        self.setFont("Helvetica", 8)
        self.setFillColor(text_color)
        self.drawRightString(558, 750, "Generated by AI Research Assistant")
        
        self.setStrokeColor(border_color)
        self.setLineWidth(0.75)
        self.line(54, 742, 558, 742)
        
        # Footer
        self.drawString(54, 40, "Confidential | Artificial Intelligence Analysis")
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 40, page_text)
        
        self.line(54, 52, 558, 52)
        
        self.restoreState()

def clean_markdown_formatting(text: str) -> str:
    """
    Convert basic markdown elements (bold, italic) to ReportLab supported HTML tags.
    Also escapes XML reserved characters.
    """
    if not text:
        return ""
    
    # Escape XML tags except tags we explicitly insert
    text = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    
    # Convert bold (**text** or __text__) to <b>text</b>
    text = re.sub(r'\*\*(.*?)\*\*', r'<b>\1</b>', text)
    text = re.sub(r'__(.*?)__', r'<b>\1</b>', text)
    
    # Convert italic (*text* or _text_) to <i>text</i>
    text = re.sub(r'\*(.*?)\*', r'<i>\1</i>', text)
    text = re.sub(r'_(.*?)_', r'<i>\1</i>', text)
    
    # Restore escaped versions of tags we want to allow (b, i)
    text = text.replace("&lt;b&gt;", "<b>").replace("&lt;/b&gt;", "</b>")
    text = text.replace("&lt;i&gt;", "<i>").replace("&lt;/i&gt;", "</i>")
    
    return text

def parse_markdown_to_flowables(markdown_content: str, styles: Any, chart_paths: List[str]) -> List[Any]:
    """
    Parse a markdown text document into a list of ReportLab Flowables.
    """
    flowables = []
    lines = markdown_content.split('\n')
    
    in_list = False
    list_items = []
    
    in_quote = False
    quote_lines = []
    
    # Precompiled styles
    body_style = styles["ReportBody"]
    h1_style = styles["ReportH1"]
    h2_style = styles["ReportH2"]
    h3_style = styles["ReportH3"]
    bullet_style = styles["ReportBullet"]
    quote_style = styles["ReportQuote"]
    
    chart_idx = 0
    
    for line in lines:
        stripped = line.strip()
        
        # Handle empty lines
        if not stripped:
            if in_list:
                # Close list block
                for item in list_items:
                    flowables.append(Paragraph(item, bullet_style))
                    flowables.append(Spacer(1, 4))
                in_list = False
                list_items = []
            if in_quote:
                # Close quote block
                quote_text = " ".join(quote_lines)
                # Render as a callout box
                t = Table([[Paragraph(quote_text, quote_style)]], colWidths=[504])
                t.setStyle(TableStyle([
                    ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F3F4F6")),
                    ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                    ('LEFTPADDING', (0,0), (-1,-1), 12),
                    ('RIGHTPADDING', (0,0), (-1,-1), 12),
                    ('TOPPADDING', (0,0), (-1,-1), 8),
                    ('BOTTOMPADDING', (0,0), (-1,-1), 8),
                    ('LINELEFT', (0,0), (0,-1), 3, colors.HexColor("#2563EB")), # Blue left border
                ]))
                flowables.append(t)
                flowables.append(Spacer(1, 10))
                in_quote = False
                quote_lines = []
            continue
            
        # Handle Blockquotes / Callouts
        if stripped.startswith('>'):
            in_quote = True
            q_line = stripped.lstrip('>').strip()
            # Strip callout indicators like [!NOTE]
            q_line = re.sub(r'^\[!(NOTE|IMPORTANT|WARNING|TIP|CAUTION)\]', '', q_line).strip()
            quote_lines.append(clean_markdown_formatting(q_line))
            continue
            
        # If we are in quote and line doesn't start with '>', close it first
        if in_quote and not stripped.startswith('>'):
            quote_text = " ".join(quote_lines)
            t = Table([[Paragraph(quote_text, quote_style)]], colWidths=[504])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F3F4F6")),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('LEFTPADDING', (0,0), (-1,-1), 12),
                ('RIGHTPADDING', (0,0), (-1,-1), 12),
                ('TOPPADDING', (0,0), (-1,-1), 8),
                ('BOTTOMPADDING', (0,0), (-1,-1), 8),
                ('LINELEFT', (0,0), (0,-1), 3, colors.HexColor("#2563EB")),
            ]))
            flowables.append(t)
            flowables.append(Spacer(1, 10))
            in_quote = False
            quote_lines = []
            
        # Handle headings
        if stripped.startswith('# '):
            flowables.append(Paragraph(clean_markdown_formatting(stripped[2:]), h1_style))
            flowables.append(Spacer(1, 10))
        elif stripped.startswith('## '):
            flowables.append(Paragraph(clean_markdown_formatting(stripped[3:]), h2_style))
            flowables.append(Spacer(1, 8))
        elif stripped.startswith('### '):
            flowables.append(Paragraph(clean_markdown_formatting(stripped[4:]), h3_style))
            flowables.append(Spacer(1, 6))
            
        # Handle list items
        elif stripped.startswith('- ') or stripped.startswith('* ') or re.match(r'^\d+\.\s', stripped):
            in_list = True
            content = re.sub(r'^(-\s|\*\s|\d+\.\s)', '', stripped)
            list_items.append(clean_markdown_formatting(content))
            
        # Handle visualizations placeholders
        elif "[Chart:" in stripped or "![Visualization]" in stripped or "[Visualization:" in stripped:
            # If we have chart paths, insert the next available chart image
            if chart_idx < len(chart_paths):
                c_path = chart_paths[chart_idx]
                if os.path.exists(c_path):
                    try:
                        img = Image(c_path, width=6*inch, height=3.8*inch)
                        flowables.append(Spacer(1, 8))
                        flowables.append(KeepTogether([img, Spacer(1, 8)]))
                        chart_idx += 1
                    except Exception as e:
                        logger.error(f"Error loading image in PDF generation: {e}")
            else:
                flowables.append(Paragraph(clean_markdown_formatting(stripped), body_style))
                flowables.append(Spacer(1, 10))
                
        # Handle normal text
        else:
            if in_list:
                for item in list_items:
                    flowables.append(Paragraph(item, bullet_style))
                    flowables.append(Spacer(1, 4))
                in_list = False
                list_items = []
                
            flowables.append(Paragraph(clean_markdown_formatting(stripped), body_style))
            flowables.append(Spacer(1, 10))
            
    # Flush remaining lists/quotes
    if in_list:
        for item in list_items:
            flowables.append(Paragraph(item, bullet_style))
            flowables.append(Spacer(1, 4))
    if in_quote:
        quote_text = " ".join(quote_lines)
        t = Table([[Paragraph(quote_text, quote_style)]], colWidths=[504])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,-1), colors.HexColor("#F3F4F6")),
            ('LINELEFT', (0,0), (0,-1), 3, colors.HexColor("#2563EB")),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('LEFTPADDING', (0,0), (-1,-1), 12),
            ('TOPPADDING', (0,0), (-1,-1), 8),
            ('BOTTOMPADDING', (0,0), (-1,-1), 8),
        ]))
        flowables.append(t)
        
    return flowables

def generate_pdf_report(topic: str, markdown_content: str, chart_paths: List[str], output_path: str) -> str:
    """
    Generates a structured, professional PDF report from the markdown contents and chart images.
    """
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    
    # Establish document setup
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=54,  # 0.75 in
        rightMargin=54,
        topMargin=72,   # 1.0 in
        bottomMargin=72
    )
    
    # Define design colors
    primary_color = colors.HexColor("#1E3A8A")   # Deep Blue
    secondary_color = colors.HexColor("#3B82F6") # Bright Blue
    charcoal = colors.HexColor("#1F2937")        # Dark Charcoal
    
    # Custom styles
    styles = getSampleStyleSheet()
    
    # Modifying default styles
    styles['Normal'].textColor = charcoal
    styles['Normal'].fontSize = 10
    styles['Normal'].leading = 14
    
    # Creating custom unique styles
    styles.add(ParagraphStyle(
        name="ReportH1",
        parent=styles['Heading1'],
        fontName="Helvetica-Bold",
        fontSize=18,
        leading=22,
        textColor=primary_color,
        spaceBefore=18,
        spaceAfter=10,
        keepWithNext=True
    ))
    
    styles.add(ParagraphStyle(
        name="ReportH2",
        parent=styles['Heading2'],
        fontName="Helvetica-Bold",
        fontSize=14,
        leading=18,
        textColor=secondary_color,
        spaceBefore=14,
        spaceAfter=8,
        keepWithNext=True
    ))
    
    styles.add(ParagraphStyle(
        name="ReportH3",
        parent=styles['Heading3'],
        fontName="Helvetica-Bold",
        fontSize=12,
        leading=16,
        textColor=charcoal,
        spaceBefore=10,
        spaceAfter=6,
        keepWithNext=True
    ))
    
    styles.add(ParagraphStyle(
        name="ReportBody",
        parent=styles['Normal'],
        spaceAfter=8
    ))
    
    styles.add(ParagraphStyle(
        name="ReportBullet",
        parent=styles['Normal'],
        leftIndent=20,
        firstLineIndent=-10,
        spaceAfter=4
    ))
    
    styles.add(ParagraphStyle(
        name="ReportQuote",
        parent=styles['Normal'],
        fontName="Helvetica-Oblique",
        fontSize=10,
        leading=14,
        textColor=colors.HexColor("#4B5563")
    ))
    
    story = []
    
    # --- 1. TITLE PAGE ---
    # Decorative Top Bar
    bar_data = [['']]
    bar_table = Table(bar_data, colWidths=[504], rowHeights=[10])
    bar_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), primary_color),
        ('BOTTOMPADDING', (0,0), (-1,-1), 0),
        ('TOPPADDING', (0,0), (-1,-1), 0),
    ]))
    story.append(bar_table)
    story.append(Spacer(1, 1.5 * inch))
    
    # Title
    title_style = ParagraphStyle(
        name="CoverTitle",
        fontName="Helvetica-Bold",
        fontSize=28,
        leading=34,
        textColor=primary_color,
        alignment=0, # Left
        spaceAfter=15
    )
    story.append(Paragraph(topic.upper(), title_style))
    story.append(Spacer(1, 10))
    
    # Subtitle
    subtitle_style = ParagraphStyle(
        name="CoverSubtitle",
        fontName="Helvetica",
        fontSize=14,
        leading=18,
        textColor=colors.HexColor("#4B5563"),
        alignment=0,
        spaceAfter=40
    )
    story.append(Paragraph("A Comprehensive Industry Insight and Research Analysis Report", subtitle_style))
    story.append(Spacer(1, 1.5 * inch))
    
    # Author & Date Information
    meta_style = ParagraphStyle(
        name="CoverMeta",
        fontName="Helvetica-Bold",
        fontSize=10,
        leading=14,
        textColor=charcoal,
    )
    story.append(Paragraph("PREPARED BY:", meta_style))
    
    author_style = ParagraphStyle(
        name="CoverAuthor",
        fontName="Helvetica",
        fontSize=11,
        leading=15,
        textColor=colors.HexColor("#4B5563"),
        spaceAfter=15
    )
    story.append(Paragraph("Autonomous AI Research Assistant", author_style))
    
    story.append(Paragraph("DATE OF GENERATION:", meta_style))
    
    import datetime
    today = datetime.datetime.now().strftime("%B %d, %Y")
    story.append(Paragraph(today, author_style))
    
    # Decorative Bottom Grid
    story.append(Spacer(1, 0.5 * inch))
    grid_data = [['']]
    grid_table = Table(grid_data, colWidths=[504], rowHeights=[4])
    grid_table.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), secondary_color),
    ]))
    story.append(grid_table)
    
    story.append(PageBreak())
    
    # --- 2. REPORT CONTENT ---
    # Parse Markdown content and add Flowables
    content_flowables = parse_markdown_to_flowables(markdown_content, styles, chart_paths)
    story.extend(content_flowables)
    
    # Build Document using NumberedCanvas
    doc.build(story, canvasmaker=NumberedCanvas)
    
    logger.info(f"Successfully generated PDF report at {output_path}")
    return output_path
